set(SOURCE_FILES_VERIFICATION_GENERIC_REF
    ${LVLX_DIR}/common.c
    ${LVLX_DIR}/encode_verification.c
    ${LVLX_DIR}/verify.c
)

add_library(${LIB_VERIFICATION_${SVARIANT_UPPER}} STATIC ${SOURCE_FILES_VERIFICATION_GENERIC_REF})
target_link_libraries(${LIB_VERIFICATION_${SVARIANT_UPPER}} ${LIB_PRECOMP_${SVARIANT_UPPER}} ${LIB_MP} ${LIB_GF_${SVARIANT_UPPER}} ${LIB_EC_${SVARIANT_UPPER}} ${LIB_HD_${SVARIANT_UPPER}})
target_include_directories(${LIB_VERIFICATION_${SVARIANT_UPPER}} PRIVATE ${INC_PUBLIC} ${INC_COMMON} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_MP} ${INC_GF} ${INC_GF_${SVARIANT_UPPER}} ${INC_EC} ${INC_HD} ${INC_VERIFICATION})
target_compile_options(${LIB_VERIFICATION_${SVARIANT_UPPER}} PRIVATE ${C_OPT_FLAGS})
target_compile_definitions(${LIB_VERIFICATION_${SVARIANT_UPPER}} PUBLIC SQISIGN_VARIANT=${SVARIANT_LOWER})
